---
- name: Install exporters on web servers
  hosts: web_servers
  become: yes

  tasks:
    - name: Download and install node exporter
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz"
        dest: /tmp/node_exporter.tar.gz
      register: node_exporter_download

    - name: Extract node exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
        extra_opts: [--strip-components=1]
        mode: '0755'
